# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apple Podcast Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apple Podcast Clone
  ## Alamofire For Easy HTTP Requests
  pod 'Alamofire', '~> 5.0.0-rc.2'

end
